# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    x86_64-linux = "1x77qpnd0lj9f6204c1gxy5pbfkvlvwws146jyd3l33ipjn8qkpr";
    aarch64-linux = "1plvs3id4cflrc2q0qskwa8cvr5mpvwa4zmp2cm6s4w29bpc5jp3";
    x86_64-darwin = "0kzk7kvlppmcrlrnsjx62bchirvrz3pc1s9l9zmrlx4xrmdy830w";
    aarch64-darwin = "08fl7j7xrkjwbbnk84x9p061zb8nypxf6lr2zzdbqq3y2w5khqhf";
  };

  urlMap = {
    x86_64-linux = "https://github.com/jphastings/jwker/releases/download/v0.2.2/jwker_Linux_x86_64.tar.gz";
    aarch64-linux = "https://github.com/jphastings/jwker/releases/download/v0.2.2/jwker_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/jphastings/jwker/releases/download/v0.2.2/jwker_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/jphastings/jwker/releases/download/v0.2.2/jwker_Darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "jwker";
  version = "0.2.2";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./jwker $out/bin/jwker
  '';

  system = system;

  meta = {
    description = "Easily convert between PEM and JWK files.";
    homepage = "https://github.com/jphastings/jwker/";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
